import { defineConfig, devices } from "@playwright/test";

const PORT = Number(process.env.E2E_PORT ?? 3100);
const BASE_URL = `http://127.0.0.1:${PORT}`;

/**
 * Point at a Chromium that is already on the machine, for environments that
 * ship one instead of letting Playwright download a matching build. Left unset,
 * Playwright uses its own browser as usual.
 */
const executablePath = process.env.PLAYWRIGHT_CHROMIUM_PATH;

/**
 * End-to-end tests run against a real production build.
 *
 * The Anthropic call is the one thing that is stubbed - the test intercepts
 * /api/analyze and replies with a canned SSE stream, so the whole flow
 * (import → statistics → consent → progress → cards → evidence → stats → PDF)
 * is exercised for real without an API key or a paid request. The PDF route is
 * not stubbed: that response really is generated by the server.
 */
export default defineConfig({
  testDir: "./e2e",
  timeout: 90_000,
  expect: { timeout: 15_000 },
  fullyParallel: false,
  workers: 1,
  reporter: [["list"]],
  use: {
    baseURL: BASE_URL,
    trace: "retain-on-failure",
    ...(executablePath ? { launchOptions: { executablePath } } : {}),
  },
  projects: [
    { name: "desktop", use: { ...devices["Desktop Chrome"] } },
    { name: "mobile", use: { ...devices["Pixel 7"] } },
  ],
  webServer: {
    command: `npx next start -p ${PORT}`,
    url: BASE_URL,
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
    env: {
      // The route needs a key present to construct its client; the request
      // itself never leaves the process because the test intercepts it.
      ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY ?? "sk-ant-e2e-placeholder",
    },
  },
});
