/**
 * Where uploaded media lives.
 *
 * Three rules, each of which exists because the alternative is a leak:
 *
 * The storage key is derived, never supplied. A client hands us a reference
 * from its own export ("photos/photo_1@01-01-2024.jpg"); we hash it together
 * with the job id and store under that. A caller cannot name the file it writes
 * or the file it reads, so no amount of `../` in an export gets anywhere.
 *
 * Files are owner- and job-scoped by path, so a key from one analysis cannot
 * resolve inside another even if it leaked.
 *
 * Nothing here is reachable over HTTP. The directory is outside `public/`, no
 * route serves it, and the only reader is the gateway running server-side.
 * Private photographs do not get a URL.
 */

import { createHash } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";

import { serverConfig } from "@/lib/config";

/**
 * The relative key for one attachment.
 *
 * Content of the reference affects only the hash, never the path shape, so a
 * reference of `../../etc/passwd` produces an ordinary hex filename like any
 * other.
 */
export function storageKeyFor(
  ownerId: string,
  jobId: string,
  reference: string,
): string {
  const digest = createHash("sha256")
    .update(`${jobId}\u0000${reference}`)
    .digest("hex")
    .slice(0, 32);
  return join(sanitiseSegment(ownerId), sanitiseSegment(jobId), digest);
}

/**
 * Strips anything that is not a plain identifier.
 *
 * Owner and job ids are generated by us and already safe; this is belt and
 * braces for the day one of them comes from somewhere else.
 */
function sanitiseSegment(value: string): string {
  const cleaned = value.replace(/[^A-Za-z0-9_-]/g, "");
  return cleaned.length > 0 ? cleaned : "unknown";
}

function rootDir(): string {
  return resolve(serverConfig().media.storageDir);
}

/** Absolute path for a key, refusing anything that escapes the root. */
function absolutePath(storageKey: string): string {
  const root = rootDir();
  const full = resolve(root, storageKey);
  if (full !== root && !full.startsWith(root + "/")) {
    throw new Error("storage key escaped the media root");
  }
  return full;
}

export async function writeMedia(
  storageKey: string,
  bytes: Uint8Array,
): Promise<void> {
  const full = absolutePath(storageKey);
  await mkdir(dirname(full), { recursive: true });
  await writeFile(full, bytes);
}

/** Reads a stored file, or null when it is not there. */
export async function readMedia(storageKey: string): Promise<Uint8Array | null> {
  try {
    const buffer = await readFile(absolutePath(storageKey));
    return new Uint8Array(buffer);
  } catch {
    return null;
  }
}

/**
 * Deletes every file belonging to one analysis.
 *
 * Called when the analysis finishes, which is the point: the bytes were needed
 * to produce the report and are not needed to keep it. Holding someone's
 * photographs after the thing that needed them is done is storing private data
 * for no purpose.
 */
export async function deleteJobMedia(ownerId: string, jobId: string): Promise<void> {
  const dir = absolutePath(join(sanitiseSegment(ownerId), sanitiseSegment(jobId)));
  await rm(dir, { recursive: true, force: true });
}
